### PR TITLE
docs(aws-lambda) add a reminding note for URI-encoded secrets in payloads

### PR DESCRIPTION
**Pull request by thibaultcha**
Follow-up doc improvement for Mashape/kong#2651

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
It would be a better improvement IMO to update all relevant entries where this encoding could occur (e.g. auth keys/tokens, where 'random' strings can be provided). BTW this is exactly why the new `random_string` only uses alphanumeric chars ;)

**Comment by thibaultcha** [comment]
Yeah, this is a start.

**Comment by thibaultcha** [comment]
(`random_string` has always returned alphanumeric chars only)

**Comment by p0pr0ck5** [comment]
(sorry, had meant the transformation of b64: https://github.com/Mashape/kong/blob/release/0.11/kong/tools/utils.lua#L211).

**Pull request merged**
