### PR TITLE
docs(*) Remove leftover Heroku and Serf references

### PR DESCRIPTION
**Pull request by hishamhm**
* Remove orphan file heroku.md, which wasn't referenced anymore.
* Remove unused serf variable for 0.11.

### CODE REVIEW

**Comment by thibaultcha** [comment]
@hishamhm Did we run a `grep` in the `docs/0.11` folder just to make sure we never reference that `serf` variable anymore? Just to be sure!

**Comment by hishamhm** [comment]
@thibaultcha yes, I did. In this repo, it appears only in `0.9.x` and `0.10.x`.

**Comment by thibaultcha** [comment]
Great! Thank you for confirming :+1:

**Comment by thibaultcha** [comment]
Manually merged to `0.11.0` with some minor tweaks to the commit messages. Thank!

**Pull request closed without merging**
