### PR TITLE
[feature] configuration reference

### PR DESCRIPTION
**Pull request by thibaultCha**
Here is the Kong configuration reference. I tried to be as inspired as possible for the intro text but well, it wasn't that efficient...

Also I am not sure about the side menu in `docs.html`.

@Nijikokun Please review, rephrase, reword :)

@thefosk I still don't know what `nginx_plus_status` really does. Could you please update the PR or explain here.

**Depends on Mashape/kong#162 being merged.**

### CODE REVIEW

**Comment by montanaflynn** [comment]
Can we fix #48 in this PR?

**Comment by Nijikokun** [comment]
Alright, on reviewing it, and yes @montanaflynn this will fix #48 

For the time being @thibaultCha `nginx_plus_status` does this if you were wondering: http://getkong.org/plugins/nginx-plus-monitoring/

**Comment by thibaultCha** [comment]
Yeah I know it's for the plugin, but I don't get why it's needed exactly.

**Comment by Nijikokun** [comment]
> No this is correct. Kong.yml is not

My apologies, I was going by kong.yml since there was no example

**Pull request merged**
