### PR TITLE
chore(documentation): Change direction to suggestion, Closes #73

### LINKED ISSUE #73: guide states adding a plugin to config, that's already added
guide suggests [adding a plugin](http://getkong.org/docs/0.2.0-2/getting-started/enabling-plugins/): `Add keyauth under the plugins_available property in your Kong instance configuration file`

however, it seems all plugins are already added and enabled by default.

### PR DESCRIPTION
**Pull request by Nijikokun**

### CODE REVIEW

**Comment by thibaultCha** [comment]
needs to be done against the 0.2.1 branch.

**Comment by Nijikokun** [comment]
Eh, it's already done, it is a very basic change.

**Comment by thibaultCha** [comment]
https://github.com/Mashape/getkong.org/pull/65/files#diff-2df8af859fe91458755a21f82ac402ddR23

**Comment by ahmadnassri** [comment]
> Eh, it's already done, it is a very basic change.

because it will be on a different file

**Comment by Nijikokun** [comment]
https://github.com/Mashape/getkong.org/commit/2aad6d6ddb709934289a33de62823f894f08dc80

**Comment by ahmadnassri** [comment]
:yellow_heart:

**Pull request merged**
