### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by ahmadnassri**
many small typo fixes and in some cases markdown/html fixes.

submitted separately (as much as possible) so can cherry-pick a merge later if one is not proper fix.

### CODE REVIEW

**Comment by thibaultCha** [comment]
squash?

**Comment by Nijikokun** [comment]
@ahmadnassri quickstart is one word.

**Comment by ahmadnassri** [comment]
> squash?

@thibaultCha yeah, but kept as is for now in case of rejecting one or more of the individual changes, so can cherry pick.

**Comment by ahmadnassri** [comment]
> @ahmadnassri quickstart can be both one word or two words, I prefer the former.

@Nijikokun I looked at other examples (quick search on google) of tech applications / projects and found "Quick Start" to be more dominant usage.

**Comment by Nijikokun** [comment]
Still prefer it as a single word looks better

**Comment by ahmadnassri** [comment]
@thibaultCha see ^ I knew they'd be need for cherry-picking :)

@Nijikokun everything else good then? want me to remove 161fdcb + 5b82b07 then flatten & mege?

**Comment by Nijikokun** [comment]
Yeah, everything else looks good :-)

**Pull request closed without merging**
