### PR TITLE
Clarify SSL plugin requirements

### PR DESCRIPTION
**Pull request by coopr**
The SSL plugin is required only for Kong versions < 0.10.0.

Additionally, the specified configuration of the SSL plugin is required only when SSL is not being terminated downstream.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
How will merging this into the master branch affect the merge of the `release/0.10` branch?

**Comment by coopr** [comment]
oh shoot, I should have PR'ed this against `release/0.10` branch? I could easily be doing it wrong.

**Comment by p0pr0ck5** [comment]
I don't actually know? @thibaultcha might have some good input, just not sure if this will result in a merge conflict.

**Comment by thibaultcha** [comment]
Just switched the base branch to release/0.10 instead.

**Comment by thibaultcha** [comment]
(I will rebase this)

**Comment by thibaultcha** [comment]
Taken care of by 8f8bb56 with the proper format we use for notes.

**Pull request closed without merging**
