### PR TITLE
release: 0.8.0

### PR DESCRIPTION
**Pull request by thibaultCha**
- [x] reference PostgreSQL support and update documentation consequently

#### TODO
- [ ] Update the AWS CF provisioning instructions to reflect Postgres support
- [ ] Update the AWS AMI installation instructions to reflect Postgres support
- [ ] Update Heroku provisioning instructions to reflect Postgres support
- [x] Mashape/docker-kong#26: 
  - [x] Change the datastore link name from `cassandra` to `kong-datatore` to reflect pluggable backend availability
  - [x] Make the `database` property of docker-kong configurable through an environment variables from `docker run`
- [x] Update the Public Lua API Reference (Kong's internals)
- [x] Update the datastore chapters in the documentation to reflect Postgres support
- [x] Update the FAQ to reflect Postgres support
  - [x] Eventually, update the diagram mentioning Cassandra

### CODE REVIEW

**Comment by sinzone** [comment]
for the last point @jitachi

**Comment by jitachi** [comment]
@sinzone when is this going to be released?

**Comment by thibaultCha** [comment]
Postgres release:

@shashiranjan84 
Any chance the CF template and AMI will be updated before the release? I mostly mean the instructions for `/install`, so I guess they need to be updated even if they're not approved by AWS directly.

@jitachi @sinzone 
Not sure updating it is essential, it's only this image:
image
If we want to update it it's only text anyways (`Cassandra` -> `DB (Cassandra/PostgreSQL`)

@thefosk 
See Mashape/docker-kong#26, but basically we could just `sed` the config file from an ENV variable (`cassandra`/`postgres`).

Review of this PR (all docs updates) and Postgres features are very much needed too.

**Comment by shashiranjan84** [comment]
@thibaultCha Will update the CF and AMI tomorrow morning.

**Comment by thibaultCha** [comment]
Can those use Amazon RDS to spawn a Postgres server? As a common practice, such server should probably create its own `kong` user, and it would be nice if such user could have a password too. SSL connection is not supported yet by the driver, but it would be nice to get that ready too. Finally, the server must also have its own database (probably should be named `kong` too) because unlike Cassandra's keyspace, Kong won't create it automatically.

**Comment by shashiranjan84** [comment]
Not sure, would need to explore the possibility. Ideally CF  should have ways to get up an Amazon RDS running like it allow all other resources.

**Comment by shashiranjan84** [comment]
@thibaultCha @thefosk I would need packaged kong-postgres  to work on Cloud Formation template.

**Comment by sinzone** [comment]
for the image i think adding "Postgres/Cassandra DB" is enough for now

**Comment by thibaultCha** [comment]
It's exactly what I said.

**Comment by sinzone** [comment]
plus add the 3 new image diagrams here: https://getkong.org/about/advantages/

**Comment by thibaultCha** [comment]
They've been updated for quite some time already now.

**Comment by sinzone** [comment]
https://github.com/Mashape/getkong.org/pull/199

**Comment by thibaultCha** [comment]
wording of that one is not so good

**Comment by sinzone** [comment]
apply fixes. but that question comes in a lot from our calls.

**Comment by thibaultCha** [comment]
It should actually be:

- Why Lua?
Because OpenResty.

- Why OpenResty?
Because it's an easy and flexible way to extend Nginx.

**Comment by thefosk** [comment]
We are ready here. @shashiranjan84 is working on the AWS stuff - we need to ping @mars for the Heroku update.

**Comment by mars** [comment]
Howdy @thefosk. Excited about the 0.8 release! You folks are making awesome progress 👍 

We have some work to get to this new version released on Heroku. The summary is:

* we still see [untraceable Cassandra errors](https://github.com/heroku/heroku-kong/issues/6) with 0.8, & (coincidentally?) the cluster looses cohesion after a few days requiring a restart
* we have Postgres working 🎸 with solid clustering, but it awaits a patch to Lua/PGMoon for SSL to work properly (required for Heroku Postgres.)

I'd love to catch up with you about this. Feel free to email me or open a new issue to discuss.

**Comment by thibaultCha** [comment]
> we still see untraceable Cassandra errors with 0.8, & (coincidentally?)

It's really tough to know if this is coming from Kong's DAO or from the Cassandra driver. My guess is with the DAO, and 0.8 comes with a slightly better one, so there might be some more informations. Another thing that could help is such a patch:

```diff
diff --git a/kong/core/cluster.lua b/kong/core/cluster.lua
index bb69b15..8db230b 100644
--- a/kong/core/cluster.lua
+++ b/kong/core/cluster.lua
@@ -82,6 +82,8 @@ local function send_keepalive(premature)
       local node = table.remove(nodes, 1)
       local _, err = dao.nodes:update(node)
       if err then
+        local inspect = require "inspect"
+        print(inspect(err))
         ngx.log(ngx.ERR, tostring(err))
       end
     end
```

This could help clarifying if the `tostring` call in the log is hiding some important parts of the error (errors returned by the C* driver in its 0.5.x version are tables with error types and codes).

> the cluster looses cohesion after a few days requiring a restart

By this, do you mean the Cassandra cluster or the Kong cluster?

> but it awaits a patch to Lua/PGMoon for SSL to work properly (required for Heroku Postgres.)

I implemented SSL connections in pgmoon at leafo/pgmoon#24, as soon as it gets accepted we'll just have to bump our version, add a few config properties, and we'll have SSL support.

**Comment by mars** [comment]
Thank you for the `inspect` tip. I will do that and follow-up in the Heroku Kong issue.

>> the cluster looses cohesion after a few days requiring a restart

> By this, do you mean the Cassandra cluster or the Kong cluster?

The Kong cluster, specifically the Admin `/cluster` API no longer lists members beyond the instance serving the request.

Get news about pgmoon+SSL 💛

**Comment by thibaultCha** [comment]
BTW, I think you'll be interested in the current work being done in the CLI, which adds support for configuration with ENV variables:

https://github.com/Mashape/kong/blob/refactor/cli/kong/conf_loader.lua#L122

And a new config file: https://github.com/Mashape/kong/blob/refactor/cli/kong.conf.default

**Comment by thibaultCha** [comment]
@mars More news! I think I have found where those errors come from, see https://gist.github.com/chrisbaldauf/f5347719313f48e0d301fd48e8afbb87

If you follow those steps, it could help us have more info about what those errors actually are about.

**Pull request merged**
