### PR TITLE
doc(plugins) sync logging plugin docs

### PR DESCRIPTION
**Pull request by p0pr0ck5**
* Missing latency field in TCP logging example
* Proper upstream_url in several logging examples
* Remove undefined authenticated_entity keys

### CODE REVIEW

**Comment by thibaultcha** [comment]
Sweet, thanks!

It all looks good except one thing: since 0.10.0, final slashes are disallowed in the `upstream_url` field of an API. Mind removing those we have in there?

**Comment by thibaultcha** [comment]
Actually, it seems the entire definition of API Objects is still for 0.9.x 😅 

Now that we have so many more fields in the API definition, this might warrant an update of the basic serializer in Kong to remove the undesired one (ex: created_at is not in the `consumer` field, but still the the `api` field...).

Side note: those logging serializers were a nice idea that wasn't entirely followed through (ability to configure more or less verbose serializers for all logging plugins), but logging plugins have became less and less of a priority... Just thought you might be curious about those.

**Comment by p0pr0ck5** [comment]
Nice catch. Re-did the `api` key for each logging example based on https://getkong.org/docs/0.10.x/admin-api/#api-object

**Comment by thibaultcha** [comment]
Thanks!

**Pull request merged**
