### PR TITLE
fix(layout) Remove the gh-star bait button

### PR DESCRIPTION
**Pull request by thibaultCha**
Finally remove this bait button, is 3000 stars enough?

### CODE REVIEW

**Comment by ahmadnassri** [comment]
@sinzone ?

**Comment by sinzone** [comment]
not yet. Devs use it as quick bookmark to view it later when they have time. it's very useful. 

![] (http://cl.ly/image/2c0x3Q3a3Z2m/Image%202015-10-26%20at%2010.45.06%20PM.png)

**Comment by thibaultCha** [comment]
The issue here is the it is next to the actual logo and screams "CLICK ME".

The screenshot you posted is a good example to follow (unlike Kong): it's non intrusive at the bottom. Which we have on the website but this removes the bait button from the header. 

On a side note, it doesn't actually star the repo, it is just a link to it.

**Comment by sinzone** [comment]
yes that's what i say.. won't auto follow. 

i agree that next to logo is weird, but till we have a new design/found a prominent place (that one in the example is right after install "main call to action" in the center) than don't remove it.

has to be somewhere in this area ![] (http://cl.ly/image/1P0P0H314109/Image%202015-10-26%20at%2011.50.09%20PM.png). do you have ideas?

**Comment by sinzone** [comment]
can be in the yellow notifo area perhaps

**Comment by ahmadnassri** [comment]
closing, since removal is not the desired result here.

**Pull request closed without merging**
