### PR TITLE
Feature(plugin) XML-threat-protection plugin

### PR DESCRIPTION
**Pull request by michallis**
Can I PR to master?

### CODE REVIEW

**Comment by michallis** [comment]
sorry wrong branch name!!!

**Comment by ahmadnassri** [comment]
@michallis can you please make a separate PR for XML and one for JSON plugin.

thanks.

**Comment by ahmadnassri** [comment]
also, reference the appropriate Kong PR in each of the docs PRs here.

**Comment by thibaultcha** [comment]
Replaced by #257

**Pull request closed without merging**
