### PR TITLE
docs(plugins) add influxdb-log plugin docs

### PR DESCRIPTION
**Pull request by WALL-E**
Update InfluxDB plugin usage guide

### CODE REVIEW

**Comment by sinzone** [comment]
@WALL-E is this updated with the latest changes?

**Comment by WALL-E** [comment]
@sinzone I will update the document as soon as possible.

**Comment by WALL-E** [comment]
@sinzone  doc has been updated

**Comment by thibaultcha** [comment]
Will be closing this for now considering we're reluctant to adding new plugins to the core as we want to take them out. Thanks.

**Pull request closed without merging**
